### ISSUE TITLE
New selz.co shortlinks does not work

### ISSUE THREAD

**Issue by arwiid** [Selz/jquery.selz#13]
My shortlinks does not work but the example product works fine, I'm on version 1.0.16. For each link I include on the page (expect the example link --> http://selz.co/1gfLTzi), I get a 404 response from Selz and a message that "404 (Not Found)", it also looks like that link is redirected to a https link what gives this message: "Refused to execute script from 'https://selz.com/sdk/products/findlegacy?url=http%3A%2F%2Fselz.co%2FVk3Tq9irr&callback=jQuery111104178243194316702_1534318862029' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled." in the console.

Heres a link to an example where the demo link is working but my product is not: [https://www.zilverzmen.se/test/kurser/example_files/](https://www.zilverzmen.se/test/kurser/example_files/)

Any insights?

Thanks!

**Comment by sampotts** [comment]
Hey, 

I've just added v1.0.17 with a few fixes in. Could you give that a go? 

Cheers
Sam

**Comment by sampotts** [comment]
Actually this looks like a data issue. We'll take a look...

**Comment by sampotts** [comment]
Sorry. Just had a quick look. If you changed that link to `https://selz.co/Vk3Tq9irr` it'll work.

**Comment by arwiid** [comment]
Thanks, https:// links works fine now in version 1.0.17 (didn't work in 1.0.16.) and it solved the reported issue.

**Comment by sampotts** [comment]
Awesome! 👍
