### ISSUE TITLE
All selz.co shortlinks have stopped working

### ISSUE THREAD

**Issue by cwhenderson20** [Selz/jquery.selz#8]
I'm not certain if this affecting just me, but I have found in the past day that all of my shortlinks have stopped working. I was on 1.0.8 and updated to the latest version (1.0.13), but the issue remains. For each link I include on the page, I get a 500 response from Selz and a message that "We couldn't find a matching item for that link" in the console. 

[Here's](http://selz.co/1A7TaYL) a link that should work correctly. [This](https://selz.com/embed/itemdata/?itemurl=http://selz.co/1A7TaYL&callback=jQuery21407369651270795012_1470784285158&_=1470784285159) is the URL that Selz attempts to fetch, which visting manually does result in an error.

I also tried making a new product, thinking maybe that only old links were affected, but the problem persists. 

Any insight into this? I also wasn't completely sure if I should report this here or directly to Selz support. 

If it helps, my site's url is https://gamewornguides.com.

Thanks!

**Comment by SamPotts** [comment]
Hey Chris, 

We're looking into this now and will get back to you.

**Comment by cwhenderson20** [comment]
Thanks! Much appreciated.

**Comment by SamPotts** [comment]
Found a fix and will be deploying shortly. I'll update this issue once it's released.

**Comment by SamPotts** [comment]
Hey @cwhenderson20 , 

We just deployed the fix and it looks like the modal is working correctly now. 👍  Apologies about that.

**Comment by cwhenderson20** [comment]
No worries, thanks for the quick fix!! 👍

**Comment by SamPotts** [comment]
Awesome looking site by the way 👍

**Comment by cwhenderson20** [comment]
Thank you!! 😄

**Comment by owise1** [comment]
This recently started happening on our site as well. The modals no longer appear and we get console messages that say "We couldn't find a matching item for that link".  Here's the page: http://thesparkmag.com/store/. Any guidance would be much appreciated.

**Comment by owise1** [comment]
Scratch that. I updated to the most recent version and it's all good now.  Thanks!

**Comment by sampotts** [comment]
Sorry about that. This was due to an infrastructure change which caused issues with certain URL formatting. We updated the CDN hosted versions of the JS but any self hosted JS needs to be updated.
